#!/bin/bash

#submit this script with: sbatch thefilename

#SBATCH --time=3:00:00   # walltime
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks=1      # limit to one node
#SBATCH --cpus-per-task=8  # number of processor cores (i.e. threads)
#SBATCH --mem-per-cpu=1700M   # memory per CPU core
#SBATCH -J "scan_higgs_at"   # job name
#SBATCH --mail-user=Jobst.Ziebell@tu-dresden.de   # email address
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE,TIME_LIMIT

cd /home/s3377910
source prepare_FS.sh
module load python/2.7.5-scipy

cd HiggsScan/compare_fs
python run_at.py pole_masses_at

exit 0


