#!/bin/bash

#submit this script with: sbatch thefilename

#SBATCH --time=50:00:00   # walltime
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks=1      # limit to one node
#SBATCH --cpus-per-task=4  # number of processor cores (i.e. threads)
#SBATCH --partition=haswell
#SBATCH --mem-per-cpu=1700M   # memory per CPU core
#SBATCH -J "scan_higgs_ms_ma2_tb_and_print_delta_lambdas"   # job name
#SBATCH --mail-user=Jobst.Ziebell@tu-dresden.de   # email address
#SBATCH --mail-type=BEGIN,END,FAIL,REQUEUE,TIME_LIMIT

cd /home/s3377910
source prepare_FS.sh
module load python/2.7.5-scipy

cd HiggsScan/compare_lambdas
python run_ms_ma2_tb.py

exit 0


